import type { FoundryDeployment } from "../../lib/api/models";
import { SESSION } from "./demo-data";

export default function SessionPanel({ selected }: { selected?: FoundryDeployment }) {
  return <section className="mt-panel grid min-h-160 min-w-0 grid-cols-[minmax(0,1fr)] grid-rows-[auto_1fr_auto]">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-edge px-5 py-3.5"><div className="flex flex-wrap items-center gap-2.5"><h2 className="text-sm font-semibold">Session</h2><span className="font-(--font-code) text-xs text-ink-muted">sess_8f21c4 · item 2 · phase 2</span></div><div className="flex gap-2">{["Attach item", "Clear"].map((label) => <button key={label} className="rounded-md border border-edge-strong px-3 py-1.5 text-xs font-medium text-ink-sub hover:border-primary-500 hover:bg-primary-500/8 focus-visible:outline-2 focus-visible:outline-primary-500">{label}</button>)}</div></header>
    <div className="grid content-start gap-5.5 px-7 py-6"><div className="grid justify-items-end gap-1.5"><div className="text-[0.6875rem] uppercase tracking-[0.18em] text-ink-muted">Student</div><div className="max-w-[min(62%,460px)] rounded-lg border border-primary-500/35 bg-primary-500/10 px-4 py-3 text-sm leading-relaxed">{SESSION.student}</div></div><div className="grid gap-1.5"><div className="text-[0.6875rem] uppercase tracking-[0.18em] text-ink-muted">Tutor · {selected?.displayName ?? "No deployment"}</div><div className="max-w-[min(72%,560px)] rounded-lg border border-edge bg-bg-inset px-4 py-3 text-sm leading-relaxed">{SESSION.tutor}</div><div className="mt-0.5 font-(--font-code) text-[0.6875rem] text-ink-muted">{SESSION.meta}</div></div><div className="grid gap-2 rounded-lg border border-dashed border-edge-strong bg-bg-elevated px-4 py-3.5"><div className="text-[0.6875rem] uppercase tracking-[0.18em] text-ink-muted">Structured output</div><pre className="min-w-0 overflow-x-auto whitespace-pre font-(--font-code) text-xs leading-relaxed text-ink-sub">{SESSION.structuredOutput}</pre></div></div>
    <div className="flex items-center gap-3 border-t border-edge px-5 py-3.5"><div className="flex-1 rounded-md border border-edge bg-bg-inset px-3 py-2.5 text-sm text-ink-muted">Send a message as the student…</div><button disabled title="Not wired up yet" className="rounded-md bg-primary-500 px-5 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-70">Run</button></div>
  </section>;
}
