<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion> 
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
     <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)\..\openapi</OpenApiDocumentsDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" Version="13.4.6" />
    <PackageReference Include="Azure.AI.OpenAI" Version="2.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="11.*-*" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="11.*-*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.*" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.*" />
    <PackageReference Include="Azure.Core" Version="1.*" />
<PackageReference Include="Azure.Identity" Version="1.*" />
  <PackageReference Include="Microsoft.Agents.AI" Version="1.*" />
  <PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TsiaCoach.Shared\TsiaCoach.Shared.csproj" />
  </ItemGroup>
</Project>
