/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weatherforecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetWeatherForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FoundryDeploymentResponse: {
            id: string;
            modelName: string;
            modelVersion: string;
            displayName: string;
            provider: components["schemas"]["ModelProvider"];
            lifecycle: components["schemas"]["ModelLifecycle"];
            supportedApis: components["schemas"]["ModelApi"][];
            operations: components["schemas"]["ModelOperation"][];
            inputModalities: components["schemas"]["ModelModality"][];
            outputModalities: components["schemas"]["ModelModality"][];
            features: components["schemas"]["ModelFeature"][];
            interactionModes: components["schemas"]["InteractionMode"][];
        };
        /** @enum {unknown} */
        InteractionMode: "RequestResponse" | "Streaming" | "Realtime";
        /** @enum {unknown} */
        ModelApi: "Responses" | "ChatCompletions" | "Embeddings" | "AnthropicMessages" | "Realtime" | "Audio";
        /** @enum {unknown} */
        ModelFeature: "ToolCalling" | "StructuredOutput" | "Reasoning" | "FileInput" | "ComputerUse" | "JsonOutput";
        /** @enum {unknown} */
        ModelLifecycle: "GenerallyAvailable" | "Preview" | "Legacy" | "Deprecated";
        /** @enum {unknown} */
        ModelModality: "Text" | "Image" | "Audio" | "Video";
        /** @enum {unknown} */
        ModelOperation: "Chat" | "Embedding" | "SpeechToText" | "TextToSpeech";
        /** @enum {unknown} */
        ModelProvider: "OpenAI" | "Anthropic" | "DeepSeek" | "Google" | "Microsoft";
        WeatherForecast: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            temperatureC: number | string;
            summary: null | string;
            /** Format: int32 */
            temperatureF?: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundryDeploymentResponse"][];
                };
            };
        };
    };
    GetWeatherForecast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherForecast"][];
                };
            };
        };
    };
}
